######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 3 20:44:14 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Object.cpp
